// <auto-generated />
using System;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(TransferenciasContext))]
    [Migration("20230515231128_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DB.Respuesta", b =>
                {
                    b.Property<int>("respuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("respuestaId"));

                    b.Property<string>("cbuDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cbuOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("resultado")
                        .HasColumnType("int");

                    b.HasKey("respuestaId");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("DB.Transferencia", b =>
                {
                    b.Property<int>("transferenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transferenciaId"));

                    b.Property<string>("cbuDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cbuOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("concepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cuilDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cuilOriginante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("respuestaId")
                        .HasColumnType("int");

                    b.HasKey("transferenciaId");

                    b.HasIndex("respuestaId");

                    b.ToTable("Transferencias");
                });

            modelBuilder.Entity("DB.Transferencia", b =>
                {
                    b.HasOne("DB.Respuesta", "respuesta")
                        .WithMany()
                        .HasForeignKey("respuestaId");

                    b.Navigation("respuesta");
                });
#pragma warning restore 612, 618
        }
    }
}
